baseURL = "https://www.bernardes.eu/"
languageCode = "fr"
DefaultContentLanguage = "fr"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true 

[params]
title = "Claudio"
author = "Claudio Bernardes"
#copyright = "2020-2021"
description = "IT, Finance & OpenSource"
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = ["post"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
# indexDateFormat = "Mon, Jan 2, 2006"
# listDateFormat = "Jan 2"
# singleDateFormat = "Mon, Jan 2, 2006"

[params.simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"


[taxonomies]
tag = "tags"
category = "categories"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/claudio-bernardes-164a6455"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/obsidienne"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "twitter"
url = "https://twitter.com/bernar_claudio"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:bernardes.claudio@gmail.com"


## Menu items

[menu]

  [[menu.main]]
  name = "Accueil"
  identifier = "accueil"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Archive"
  weight = 200
  identifier = "archive"
  url = "/post/"

  [[menu.main]]
  name = "À propos"
  weight = 300
  identifier = "à propos"
  url = "/about/"

