baseURL = "https://obsidienne.github.io/"
title = "Claudio Bernardes"
languageCode = "fr"
enableInlineShortcodes = true

summarylength = 10
enableEmoji = true

theme = "soho"
disableKinds = ['taxonomy', 'taxonomyTerm']


defaultContentLanguage = "fr"


### Français ###

[languages.fr]
  languageName = "Français"
  languageCode = "fr"
  weight = 1
[languages.fr.params]
  description = "Chef de Projet et Passionné d'Open Source"
[[languages.fr.menu.main]]
  name = "CV"
  weight = 100
  identifier = "resume"
  url = "https://obsidienne.github.io/resume/"
[[languages.fr.menu.main]]
  name = "Articles"
  weight = 200
  identifier = "posts"
  url = "/posts/"
[[languages.fr.menu.main]]
  name = "Liens"
  identifier = "links"
  weight = 300
  url = "/links/" 

### English ###

[languages.en]
  languageName = "English"
  languageCode = "en"
  weight = 2
[languages.en.params]
  description = "Project Manager and open source enthusiast"
[[languages.en.menu.main]]
  name = "Resume"
  weight = 100
  identifier = "resume"
  url = "https://obsidienne.github.io/resume/"
[[languages.en.menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"
[[languages.en.menu.main]]
  name = "Links"
  identifier = "links"
  weight = 300
  url = "/links/"


[params]
author = "Claudio Bernardes"


## Set one of:
# gravatar = "soho@example.com"
profilePicture = "images/profile.jpg"

copyright = "Claudio Bernardes"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"

## Set custom theme color.
# themeColor = "#fc2803"

customCss = ["css/blog.css"]
customJs = ["js/blog.js"]

## Set as many as you want.
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/claudio-bernardes-164a6455"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/obsidienne"


[[params.socialIcons]]
icon = "fa-twitter"
title = "Twitter"
url = "https://twitter.com/bernar_claudio"

[markup]
  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true # if false, you need to provide you own custom CSS
  style = "monokai"
  tabWidth = 4